#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import pylab as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"
test -e test.png && rm test.png

# attempt at solving imagemagick policy.xml issue
cp /etc/ImageMagick-6/policy.xml /tmp
sed -i '/  <policy domain="coder" rights="none" pattern="PDF" \/>/c\  <policy domain="coder" rights="read | write" pattern="PDF" \/>' /tmp/policy.xml
MAGICK_CONFIGURE_PATH='/tmp/:/etc/ImageMagick-6/' identify -list policy
MAGICK_CONFIGURE_PATH='/tmp/:/etc/ImageMagick-6/' identify -list resource